/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.exchangeratestask;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test
    void appHasAGreeting() {
        Application classUnderTest = new Application();
        assertNotNull(classUnderTest.getClass());
    }
}
